services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: smart-mqtt-broker
    ports:
      - "1883:1883"   # Porta MQTT
      - "9001:9001"   # Porta WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always